package httpapi

import "net/http"

// route is one entry of the API: the method and path it answers, the handler
// that serves it, and a one-line description.
//
// This table is the single source for both the mux registration and the /v1
// index, and it also drives the OpenAPI document generated by
// cmd/openapi-gen. Keeping one list rather than three means a new endpoint
// cannot be wired up without also being documented and discoverable.
type route struct {
	Method      string
	Path        string
	Description string
	// Handler is a method expression, so the table can name handlers without
	// a server to bind them to. register supplies the receiver.
	Handler func(*Server, http.ResponseWriter, *http.Request)
}

// routeTable lists every endpoint the service answers, in the order they
// should appear in the index and the documentation.
//
// It is a function rather than a package variable because the index handler is
// itself one of the entries and reads the table to build its response, which a
// variable initialiser cannot express: Go would see the cycle and refuse. The
// table is short and only built at startup and on an index request.
func routeTable() []route {
	return []route{
		{http.MethodGet, healthPath, "Liveness and readiness", (*Server).handleHealth},
		{http.MethodGet, "/v1", "This index", (*Server).handleIndex},
		{http.MethodGet, "/v1/license", "Licence terms and source location", (*Server).handleLicense},
		{http.MethodGet, openAPIPath, "This OpenAPI document", (*Server).handleOpenAPI},
		{http.MethodGet, "/v1/reference/{topic}", "Supported bodies, signs, house systems, aspects and ayanamshas", (*Server).handleReference},
		{http.MethodPost, "/v1/time", "Resolve a local date and time into an instant and a Julian Day", (*Server).handleTime},
		{http.MethodPost, "/v1/natal", "Cast a birth chart: bodies, houses, aspects and dignities", (*Server).handleNatal},
		{http.MethodPost, "/v1/transits", "The sky at a moment and its aspects to a birth chart", (*Server).handleTransits},
		{http.MethodPost, "/v1/synastry", "Aspects between two birth charts", (*Server).handleSynastry},
		{http.MethodPost, "/v1/composite", "A relationship chart, by midpoint or Davison", (*Server).handleComposite},
		{http.MethodPost, "/v1/progressions", "A birth chart moved forward, by secondary progression or solar arc", (*Server).handleProgressions},
		{http.MethodPost, "/v1/returns", "Solar and lunar return charts", (*Server).handleReturns},
		{http.MethodPost, "/v1/ephemeris", "Positions at regular intervals across a span", (*Server).handleEphemeris},
		{http.MethodPost, "/v1/moon/phases", "New, first quarter, full and last quarter moons", (*Server).handleMoonPhases},
		{http.MethodPost, "/v1/retrogrades", "Stretches of backward motion, with their stations", (*Server).handleRetrogrades},
		{http.MethodPost, "/v1/eclipses", "Solar and lunar eclipses", (*Server).handleEclipses},
		{http.MethodPost, "/v1/rise-set", "Rise, set and meridian crossings at a place", (*Server).handleRiseSet},
	}
}

// register wires every entry of routeTable into a mux, plus the catch-all 404.
func (s *Server) register(mux *http.ServeMux) {
	for _, rt := range routeTable() {
		handler := rt.Handler
		mux.HandleFunc(rt.Method+" "+rt.Path,
			func(w http.ResponseWriter, r *http.Request) { handler(s, w, r) })
	}
	// Anything else is a 404 in problem+json rather than the plain text
	// ServeMux would produce.
	mux.HandleFunc("/", s.handleNotFound)
}
